IDENTITY(1,1) é o auto incremente das tabelas

SCRIPT

CREATE DATABASE BOTECO

CREATE TABLE TBLPESSOAFISICA(
  IDPESSOA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  CPF CHAR(11) NOT NULL,
  DATANACIMENTO DATE NOT NULL

)

CREATE TABLE TBLTELEFONETIPO(
  IDTELEFONETIPO INT PRIMARY KEY NOT NULL,
  DESCRICAO VARCHAR(50) NOT NULL

)

CREATE TABLE TBLTELEFONE(
  IDTELEFONE INT PRIMARY KEY NOT NULL,
  IDPESSOA INT NOT NULL FOREIGN KEY REFERENCES TBLPESSOAFISICA(IDPESSOA),
  IDTELEFONETIPO INT NOT NULL FOREIGN KEY REFERENCES TBLTELEFONETIPO(IDTELEFONETIPO),
  DDD VARCHAR(4) NOT NULL,
  PREFIXO VARCHAR(4) NOT NULL,
  PRINCIPAL BIT NOT NULL

)