CREATE DATABASE BDTrigger
USE BDTrigger

CREATE TABLE CADALUNO(
   IDAluno INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
   Nome VARCHAR(50) NOT NULL,
   Sobrenome VARCHAR(50) NOT NULL,
   DataDeAprovacao DATETIME
)

CREATE TABLE SENDEMAILS(
  IDMail INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  EmailDestino VARCHAR(100) NOT NULL,
  Assunto VARCHAR(200) NOT NULL,
  BodyEmail VARCHAR(MAX)
)

