CREATE DATABASE LOJAINFO

USE LOJAINFO teste

CREATE TABLE PEDIDOS(
   IDPedidos INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
   IDProdutos INT NOT NULL FOREIGN KEY REFERENCES PRODUTOS(IDProdutos),
   IDPESSOA INT NOT NULL FOREIGN KEY REFERENCES PESSOAS(IDPessoas),
   --Discricao VARCHAR(100) NOT NULL,
   --Nome VARCHAR(100) NOT NULL,
   Quantidade INT NOT NULL,
   Valor FLOAT
)


CREATE TABLE PRODUTOS(
  IDProdutos INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  Descricao VARCHAR(100) NOT NULL
)

CREATE TABLE PESSOAS(
  IDPessoas INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  Nome VARCHAR(100) NOT NULL,
  CPF VARCHAR(12) NOT NULL
)


-- ALTER TABLE ADD COLUNAS
ALTER TABLE PEDIDOS ADD Quantidade INT NOT NULL

INSERT INTO PESSOAS(Nome,CPF) VALUES('Lucas','131654635463')
INSERT INTO PESSOAS(Nome,CPF) VALUES('Carlos','634466546545')
-- CHECK OUT
SELECT * FROM PESSOAS

INSERT INTO PRODUTOS(Descricao) VALUES('Mouse')
INSERT INTO PRODUTOS(Descricao) VALUES('Teclado')
-- CHECK OUT
SELECT * FROM PRODUTOS


-- JOIN
-- The business leaders joined together to fight poverty.
-- Would you like to join us?

SELECT
     PEDIDOS.IDPedidos,
	 PEDIDOS.IDProdutos,
	 PRODUTOS.Descricao,
	 PEDIDOS.IDPESSOA,
	 PESSOAS.Nome,
	 PESSOAS.CPF,
	 PEDIDOS.Quantidade,
	 PEDIDOS.Valor
FROM PEDIDOS
       JOIN 
	   PESSOAS ON PEDIDOS.IDPESSOA = PESSOAS.IDPessoas
	   JOIN
	   PRODUTOS ON PEDIDOS.IDProdutos = PRODUTOS.IDProdutos


